// <auto-generated />
namespace DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Added2LinkTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added2LinkTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201905281730086_Added2LinkTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
